name: ffmpeg
on:
  push:
    paths:
      - ffmpeg/**
      - .github/workflows/ffmpeg.yml
  pull_request:
    paths:
      - ffmpeg/**
      - .github/workflows/ffmpeg.yml
  workflow_dispatch:
env:
  CI_DEPLOY_NEED_GCC: 1
  CI_DEPLOY_MODULE: ${{ github.workflow }}
  CI_DEPLOY_PLATFORM: ${{ github.job }}
  CI_DEPLOY_SETTINGS: ${{ secrets.CI_DEPLOY_SETTINGS }}
  CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
  CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
  STAGING_REPOSITORY: ${{ secrets.STAGING_REPOSITORY }}
jobs:
  #linux-x86:
  #  runs-on: ubuntu-20.04
  #  strategy:
  #    matrix:
  #      ext: [""]
  #  steps:
  #    - uses: grill2010/javacpp-presets/.github/actions/deploy-ubuntu@enable_vaapi_1.5.10
  linux-x86_64:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        ext: [""]
    steps:
      - uses: grill2010/javacpp-presets/.github/actions/deploy-ubuntu@enable_vaapi_1.5.10
  #windows-x86:
  #  runs-on: windows-2019
  #  strategy:
  #    matrix:
  #      ext: [""]
  #  steps:
  #    - uses: grill2010/javacpp-presets/.github/actions/deploy-windows@ffmpeg_patch
  #windows-x86_64:
  #  runs-on: windows-2019
  #  strategy:
  #    matrix:
  #      ext: [""]
  #  steps:
  #    - uses: grill2010/javacpp-presets/.github/actions/deploy-windows@ffmpeg_patch
  #redeploy:
  #  needs: [linux-x86_64, windows-x86_64]
  #  runs-on: ubuntu-20.04
  #  steps:
  #    - uses: grill2010/javacpp-presets/.github/actions/redeploy@ffmpeg_patch
