name: ffmpeg
on:
  push:
    paths:
      - ffmpeg/**
      - .github/workflows/ffmpeg.yml
  pull_request:
    paths:
      - ffmpeg/**
      - .github/workflows/ffmpeg.yml
  workflow_dispatch:
env:
  CI_DEPLOY_NEED_GCC: 1
  CI_DEPLOY_MODULE: ${{ github.workflow }}
  CI_DEPLOY_PLATFORM: ${{ github.job }}
  CI_DEPLOY_SETTINGS: ${{ secrets.CI_DEPLOY_SETTINGS }}
  CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
  CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
  STAGING_REPOSITORY: ${{ secrets.STAGING_REPOSITORY }}
jobs:
#  android-arm:
#    runs-on: ubuntu-22.04
#    strategy:
#      matrix:
#        ext: ["", -gpl]
#    steps:
#      - uses: grill2010/javacpp-presets/.github/actions/deploy-ubuntu@enable_vaapi_temp
  android-arm64:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        ext: ["", -gpl]
    steps:
      - uses: grill2010/javacpp-presets/.github/actions/deploy-ubuntu@enable_vaapi_temp
#  android-x86:
#    runs-on: ubuntu-22.04
#    strategy:
#      matrix:
#        ext: ["", -gpl]
#    steps:
#      - uses: grill2010/javacpp-presets/.github/actions/deploy-ubuntu@enable_vaapi_temp
  android-x86_64:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        ext: ["", -gpl]
    steps:
      - uses: grill2010/javacpp-presets/.github/actions/deploy-ubuntu@enable_vaapi_temp
#  linux-armhf:
#    runs-on: ubuntu-22.04
#    strategy:
#      matrix:
#        ext: ["", -gpl]
#    steps:
#      - uses: grill2010/javacpp-presets/.github/actions/deploy-ubuntu@enable_vaapi_temp
  linux-arm64:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        ext: ["", -gpl]
    steps:
      - uses: grill2010/javacpp-presets/.github/actions/deploy-ubuntu@enable_vaapi_temp
  linux-ppc64le:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        ext: ["", -gpl]
    steps:
      - uses: grill2010/javacpp-presets/.github/actions/deploy-ubuntu@enable_vaapi_temp
#  linux-x86:
#    runs-on: ubuntu-22.04
#    strategy:
#      matrix:
#        ext: ["", -gpl]
#    steps:
#      - uses: grill2010/javacpp-presets/.github/actions/deploy-ubuntu@enable_vaapi_temp
  linux-x86_64:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        ext: ["", -gpl]
    steps:
      - uses: grill2010/javacpp-presets/.github/actions/deploy-ubuntu@enable_vaapi_temp
  macosx-arm64:
    runs-on: macos-12
    strategy:
      matrix:
        ext: ["", -gpl]
    steps:
      - uses: grill2010/javacpp-presets/.github/actions/deploy-macosx@enable_vaapi_temp
  macosx-x86_64:
    runs-on: macos-12
    strategy:
      matrix:
        ext: ["", -gpl]
    steps:
      - uses: grill2010/javacpp-presets/.github/actions/deploy-macosx@enable_vaapi_temp
#  windows-x86:
#    runs-on: windows-2019
#    strategy:
#      matrix:
#        ext: ["", -gpl]
#    steps:
#      - uses: grill2010/javacpp-presets/.github/actions/deploy-windows@enable_vaapi_temp
  windows-x86_64:
    runs-on: windows-2019
    strategy:
      matrix:
        ext: ["", -gpl]
    steps:
      - uses: grill2010/javacpp-presets/.github/actions/deploy-windows@enable_vaapi_temp
  redeploy:
#    needs: [android-arm, android-arm64, android-x86, android-x86_64, linux-armhf, linux-arm64, linux-ppc64le, linux-x86, linux-x86_64, macosx-arm64, macosx-x86_64, windows-x86, windows-x86_64]
    needs: [android-arm64, android-x86_64, linux-arm64, linux-ppc64le, linux-x86_64, macosx-arm64, macosx-x86_64, windows-x86_64]
    runs-on: ubuntu-22.04
    steps:
      - uses: grill2010/javacpp-presets/.github/actions/redeploy@enable_vaapi_temp
